# Generated by Django 3.2.12 on 2022-10-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='FormInputQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Питання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignmentForm.formmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FormFileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Питання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignmentForm.formmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FormChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Питання')),
                ('is_multiple_answer', models.BooleanField(default=False, verbose_name='Питання має декілька відповідей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignmentForm.formmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FormChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Відповідь')),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignmentForm.formchoicequestion')),
            ],
        ),
    ]
