# Generated by Django 4.1.2 on 2022-12-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentForm', '0002_remove_formchoiceoption_form_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formchoiceoption',
            name='assignment',
        ),
        migrations.AddField(
            model_name='formchoiceoption',
            name='choice_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignmentForm.formchoicequestion'),
            preserve_default=False,
        ),
    ]
