env:
  browser: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
rules:
  react-hooks/exhaustive-deps:
    - error
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - error
    - allow:
        - warn
        - error
  arrow-parens:
    - error
    - always
  no-else-return:
    - error
    - allowElseIf: false
  jsx-quotes:
    - error
    - prefer-double
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowTypedFunctionExpressions: true
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  import/no-unresolved:
    - off
  import/no-default-export:
    - error
