# Generated by Django 4.1.2 on 2022-10-10 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_alter_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='evaluators',
            field=models.ManyToManyField(blank=True, null=True, related_name='evaluators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
