# Generated by Django 4.1.2 on 2022-11-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_creator_remove_lecture_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
    ]
