# Generated by Django 4.1.2 on 2022-12-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignmentanswer_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentinputanswer',
            name='answer',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
