# Generated by Django 4.1.2 on 2022-10-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Модератор'), ('lecturer', 'Викладач'), ('user', 'Користувач')], default='user', max_length=55),
        ),
    ]
